name = "aimagica-pages"
compatibility_date = "2024-01-01"

# Pages 部署配置
[env.production]
name = "aimagica-pages"

# 构建配置
[build]
command = "npm run build:pages"
destination = "./out"

# 头部配置
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Cache-Control = "public, max-age=3600"

[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.png"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.jpg"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.jpeg"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.svg"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# 重定向配置
[[redirects]]
from = "/api/*"
to = "https://aimagica-api.your-domain.workers.dev/api/:splat"
status = 308

# SPA 路由配置
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
conditions = {if = "path !~ \\.(js|css|png|jpg|jpeg|svg|ico|json|xml|txt)$"} 