name = "aimagica-pages"
compatibility_date = "2024-12-06"

# Cloudflare Pages 静态网站配置
pages_build_output_dir = "out"

# 明确指定这是静态网站，不使用next-on-pages
[vars]
STATIC_SITE = "true"
FRAMEWORK = "static"
DISABLE_NEXT_ON_PAGES = "true"

[env.production]
name = "aimagica-pages"